
import { PERMISSIONS } from '~/utils/permissions'
import { ROLES } from '~/utils/role'

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE
  ],

  [ROLES.CASHIER]: [PERMISSIONS.EMPLOYEE_VIEW],

  [ROLES.BARISTA]: [PERMISSIONS.EMPLOYEE_VIEW],

  [ROLES.WAITER]: [PERMISSIONS.EMPLOYEE_VIEW]
}